version: '3.2'
services:
  node:
    build: services/node
    container_name: node
    volumes:
    - type: bind
      source: ./src/site
      target: /var/www/site/
    - type: bind
      source: ./logs/node-logs
      target: /root/.npm/_logs
    working_dir: /var/www/site/
    depends_on: 
    - mongo
    ports:
    - 80:80
    - 8080:8080
    command: npm start
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
